### ISSUE TITLE
安装后，状态栏字体变白

### ISSUE THREAD

**Issue by seasonstar** [sunlu/cordova-plugin-xgpush#2]
安装后，app状态栏字体变白。不应该影响到才对

**Comment by sunlu** [comment]
@seasonstar 状态栏显示的通知标题、内容字体么？

**Comment by seasonstar** [comment]
@sunlu 不是，是ios最上面那条显示网络时间电源的状态栏

**Comment by sunlu** [comment]
@seasonstar 抱歉，对IOS不是太熟，代码都是从SDK原demo中拷过来的，在IOS下没有做太多测试，
如果说是代码中有修改字体颜色，可以看看
https://github.com/sunlu/cordova-plugin-xgpush/blob/master/src/ios/CDVXGPushPlugin.m 文件中代码
